### ISSUE TITLE
Some currencies have wrong number of decimal places

### ISSUE THREAD

**Issue by Green-Angry-Bird** [typelevel/squants#144]
The Currencies JPY and KRW should have zero decimal places (they are incorrectly set to 2 decimal places).

**Comment by Green-Angry-Bird** [comment]
That was amazingly fast guys, thanks. Any idea when we can see a new version for sbt?

**Comment by golem131** [comment]
@Green-Angry-Bird after 143 will be merged, i think first release may be published
