### ISSUE TITLE
Read currency decimals from `java.util.Currency`

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#146]
Related to #145 . The JVM has a class and method to find the decimals for each currency:

https://docs.oracle.com/javase/7/docs/api/java/util/Currency.html#getDefaultFractionDigits()

Should the decimals defined on https://github.com/typelevel/squants/blob/master/shared/src/main/scala/squants/market/Money.scala#L379 be read using this method?

I'm not sure if I want to depend on an old java class but perhaps is the correct thing

**Comment by golem131** [comment]
@cquiroz as JDK 7 EOL now, may be better use JDK 8 API?

**Comment by cquiroz** [comment]
@golem131 It is the same on jdk 1.8. Those APIs are very old on the JDK and don't change much

**Comment by golem131** [comment]
@cquiroz we can try, but what about Scala.js, for example?

**Comment by cquiroz** [comment]
there is support for scala.js on https://github.com/cquiroz/scala-java-locales
Again I'm raising the issue for completness, but I'm hesitant about going this way, it maybe overkill.
Good to keep it in mind though

**Comment by derekmorr** [comment]
I think it might be overkill, but I'm not opposed to it. If someone wants to submit a PR, I'll review.

**Comment by cquiroz** [comment]
The more I think about it, yeah, it is probably overkill and `Currency` is not exactly a pure class. Also the dependency on `scala-java-locales` would be quite large for what we get out of it
