### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#150]
I'd like to make the master branch protected. This way accidental commits are avoided and all the changes must come through a PR and tests must pass as well as requiring at least one approval:

https://help.github.com/articles/about-protected-branches/

What do you think?

**Comment by darkfrog26** [comment]
I agree.  With as many contributors as there are to this project nobody should be making direct commits, they should only come from PRs.

**Comment by derekmorr** [comment]
Agreed.

**Comment by garyKeorkunian** [comment]
Agreed.

**Comment by cquiroz** [comment]
Done!
