### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#168]
We have a few updates over version 1.0.0 and at some moment we should release. Any opinions on when to do it? Should we wait for more changes?

In the interim I made a SNAPSHOT release

**Comment by darkfrog26** [comment]
My belief about releases is that they should be as frequent as possible.  Meaning, as long as the code is stable and covered by tests, then release immediately when new functionality has been added.

**Comment by derekmorr** [comment]
I have no more pending changes. I'm fine releasing a 1.x soon.

**Comment by darkfrog26** [comment]
Regarding version numbers 0.0.x released should be bug fixes, and 0.x.0 releases should contain new functionality, and x.0.0 releases should contain major breaking changes.  Is there agreement on this paradigm?

**Comment by cquiroz** [comment]
Sounds good to me. the next release should be 1.1.0 as we have new functionality

**Comment by cquiroz** [comment]
Version 1.1.0 was released and trunk set to 1.2.0-SNAPSHOT
