### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#191]
It seems we have several improvement for a new release. Please let me know if you are ok making a next release or if we should wait for some changes

**Comment by derekmorr** [comment]
I have few small changes in the queue which I'll submit this week:

* tut integration
* more doc fixes
* more compiler warning fixes (unused imports, ignored values, etc)
* change default compiler warning flags

None of these are a blocker, so we absolutely need to get 1.2.0 out this week, that's fine.

**Comment by cquiroz** [comment]
I don't think there is an urgent hurry, unless some of our latest contributors need a release soon

Otherwise we can wait

**Comment by derekmorr** [comment]
We also need to decide how to resolve #184 so that @cranst0n can release pureconfig-squants.

**Comment by cranst0n** [comment]
It's not really a blocker for the pureconfig stuff. I've already got a PR that has a lot of machinery but certainly works.
