### ISSUE TITLE
Parsing tuples only works if the value is a double

### ISSUE THREAD

**Issue by derekmorr** [typelevel/squants#198]
According to the README, this should work:

```scala
val power = Power((40, "MW"))
```

but it doesn't:

```scala
% sbt squantsJVM/console
<snip>
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> val power = Power((40, "MW"))
scala.MatchError: (40,MW) (of class scala.Tuple2)
  at squants.Dimension$class.parse(Dimension.scala:58)
  at squants.energy.Power$.parse(Power.scala:60)
  at squants.energy.Power$$anonfun$apply$1.apply(Power.scala:63)
  at squants.energy.Power$$anonfun$apply$1.apply(Power.scala:63)
  ... 42 elided
```
`Dimension.parse()` only works on `Tuple2[Double, String]` : https://github.com/typelevel/squants/blob/master/shared/src/main/scala/squants/Dimension.scala#L58

**Comment by derekmorr** [comment]
Looks like this code never worked - https://github.com/typelevel/squants/commit/5d401bbfd21d2926a0d02b86c1b6af0f949bbaa0#diff-267437a6f42ae1f1a3b818a848f30a3e

It looks like Scala doesn't widen numeric arguments when they're part of a tuple.

**Comment by cquiroz** [comment]
I guess we should take that out of the README

**Comment by derekmorr** [comment]
Well, I'm trying to find a way of fixing it.

The quick and dirty approach is something like this:

```scala
 protected def parse(value: Any) = value match {
    case s: String              ⇒ parseString(s)
    case (v: Byte, u: String) ⇒ parseTuple(v.toDouble, u)
    case (v: Short, u: String) ⇒ parseTuple(v.toDouble, u)
    case (v: Int, u: String) ⇒ parseTuple(v.toDouble, u)
    case (v: Long, u: String) ⇒ parseTuple(v.toDouble, u)
    case (v: Float, u: String) ⇒ parseTuple(v.toDouble, u)
    case (v: Double, u: String) ⇒ parseTuple(v, u)
}
```
which just seems silly. We should be able to use a numeric typeclass, but my scala-foo is failing me.

I'm not sure how to rewrite the match to require a `Numeric` instance for the first element of the tuple. I tried something like `protected def parse[N](value: Any)(implicit numeric: Numeric[N])` but that, predictably, produced tons of compiler errors.

**Comment by derekmorr** [comment]
Another approach would to get rid of the `Dimension.parse()` function, make `Dimension.parseString()` `Dimension.parseTuple()` protected, and have the Dimension subtypes override apply and call into them directly.

For example:

```scala
object Information extends Dimension[Information] with BaseDimension {
 ...
  def apply(s: String) = parse(s)
  def apply[N](tup: Tuple2[N, String])(implicit num: Numeric[N]) = parseTuple(tup._1, tup._2)
  ...
}
```

then in the REPL this works:

```scala
scala> Information("500 MiB")  // String parsing as exists now
res0: scala.util.Try[squants.information.Information] = Success(500.0 MiB)

scala> Information((500, "MiB"))  // tuple parsing, but with a non-double numeric value
res1: scala.util.Try[squants.information.Information] = Success(500.0 MiB)

scala> Information(("foobar", "MiB")) // non-sense tuples still don't compile
<console>:208: error: could not find implicit value for parameter num: Numeric[String]
       Information(("foobar", "MiB"))
                  ^
scala> Information((BigDecimal(500), "MiB")) // we gain the ability to parse numeric types that aren't AnyVals
res2: scala.util.Try[squants.information.Information] = Success(500.0 MiB)
```

This approach breaks binary compatibility. On the upside, we make the `apply()` functions more similar to the implicit conversions, which already operate on any numeric types.

For now, it might be best to hold off on this version, since it breaks binary compatibility. We can revisit it in 2.x if we replace `double` as the underlying numeric type. In the meantime, we could do the approach I outlined in the comment above, since it doesn't break binary compatibility.
