### ISSUE TITLE
Problem using squants typeclasses

### ISSUE THREAD

**Issue by bbarker** [typelevel/squants#229]
I had the following odd situation when switching to Linux:

```scala
import squants.time._
import squants.time.TimeConversions._

class Main {
  var conceptionTime: Time = -1 nanoseconds
}

object Main {

  def main(args: Array[String]): Unit = {
    val thisMain = new Main
  }

}
```

This simple use of the type classes in squants yields the error:

```
Error:(7, 33) value nanoseconds is not a member of Int
  var conceptionTime: Time = -1 nanoseconds
```

The same code was working for me earlier today on Windows (and in a much larger project). I've tried various releases of Squants (1.2.0, 1.3.0-SNAPSHOT), and Scala 2.11 and 2.12:

https://github.com/bbarker/ProjectGists/tree/master/Scala/SquantsConversions

While I doubt the use of Linux is the underlying reason for the issue, I can't think of what else in the environment might cause the issue.

**Comment by derekmorr** [comment]
This looks like a scoping issue. I can make the above code compile on Linux (Mint 18) if I chance it to this:

```scala
import squants.time._

class Main {
  import squants.time.TimeConversions._  // restrict the scope of the implicit conversions
  var conceptionTime: Time = -1 nanoseconds
}
```

or to this:

```scala
import squants.time.TimeConversions._

class Main {
  var conceptionTime = -1 nanoseconds // remove the Time type annotation
}

**Comment by bbarker** [comment]
That works for me, though I don't quite understand why yet. Also, removing the wildcard import for `squants.time` seems to work:

```scala
import squants.time.Time
import squants.time.TimeConversions._

class Main {
  var conceptionTime: Time = -1.0 nanoseconds
}

object Main {

  def main(args: Array[String]): Unit = {
    val thisMain = new Main
  }

}
```

**Comment by bbarker** [comment]
OK, nothing to do with Linux! I has misinterpreted the issue. I had gone all day on my Windows system without actually building as I was just initiating a major refactor using squants. IntelliJ doesn't actually notice the issue.
