### ISSUE TITLE
MoneyNumeric appears to not behave correctly

### ISSUE THREAD

**Issue by bbarker** [typelevel/squants#231]
```scala
import squants.mass.{Kilograms, Mass}
import squants.mass.MassConversions.MassNumeric
import squants.market.{Money, USD}
import squants.market.MoneyConversions.MoneyNumeric

class Main {}
object Main {
  def main(args: Array[String]): Unit = {
    val massList = List(Kilograms(1), Kilograms(2))
    val moneyList = List(USD(1), USD(2))
    val massSum = massList.sum
//    val moneySum = moneyList.sum
  }

}
```

Uncommenting `val moneySum = moneyList.sum`  results in:

```
[error] Main.scala:13: could not find implicit value for parameter num: Numeric[squants.market.Money]
[error]     val moneySum = moneyList.sum
[error]                              ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed May 3, 2017 9:07:33 PM
``` 

As can be seen, the same problem does not exist for massSum.

**Comment by derekmorr** [comment]
This is documented behavior of `MoneyNumeric`. From the Readme:

The MoneyNumeric implementation is a bit different than the implementations for other quantity types in a few important ways.

MoneyNumeric is a class, not an object like the others.
To create a MoneyNumeric value there must be an implicit MoneyContext in scope.
The MoneyContext must contain applicable exchange rates if you will be applying cross-currency Numeric ops.
The following code provides a basic example for creating a MoneyNumeric:
```scala
import squants.market.defaultMoneyContext
import squants.market.MoneyConversions._
import squants.market.USD
implicit val moneyContext = defaultMoneyContext
scala> implicit val moneyNum = new MoneyNumeric()
moneyNum: squants.market.MoneyConversions.MoneyNumeric = MoneyNumeric(MoneyContext(DefaultCurrency(USD),Currencies(ARS,AUD,BRL,BTC,CAD,CHF,CLP,CNY,CZK,DKK,EUR,GBP,HKD,INR,JPY,KRW,MXN,MYR,NOK,NZD,RUB,SEK,USD,XAG,XAU),ExchangeRates(),AllowIndirectConversions(true)))

scala> val sum = List(USD(100), USD(10)).sum
sum: squants.market.Money = 110.0 USD
```

**Comment by derekmorr** [comment]
Just to clarify, the reason for the difference in behavior is that money operations might require access to the exchange rates. 

For example, `List(5.miles, 3.kilometers).sum` works b/c the conversion factor for miles and km is known at compile-time. But `List(5.USB, 3.EUR).sum` requires an exchange rate, hence the need for money context.

We might be able to special-case when we're adding the same currencies (`List(5.USB, 5.USB).sum`), but I think that would require more information at the type-level about currencies. Depending on how that's implemented, it might need to wait for 2.x.

**Comment by bbarker** [comment]
Thanks for the explanation! I'll give it a try soon; meanwhile, not sure if it makes sense to leave the issue open - happy if you close it, unless you want to update the description to match the functionality for 2.x.

**Comment by derekmorr** [comment]
Ok I'll close it.
