### ISSUE TITLE
Next release 1.3.0

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#232]
We have several important changes in the code and on PRs. We should plan to do a release once #215, #219 and #227 are merged

**Comment by cquiroz** [comment]
Should we start releasing now that there are no PRs pending?

**Comment by derekmorr** [comment]
I have to push docs for formatters. Meant to get to that last night but ended up working on pureconfig. I'll get to it tonight. 

Do we want to try to fix any other issues for this release?

**Comment by cquiroz** [comment]
It is up to us, at least personally i don't have the need to fix any of them

**Comment by derekmorr** [comment]
Did we want to fix #242 and #243 in 1.3.0 or wait?

**Comment by cquiroz** [comment]
Given that you reported those I'll leave it to you to decide if you want to submit PRs for those. I can make a release any time

**Comment by derekmorr** [comment]
I have a use for them in projects at work, and they look like a quick fix. If I get to it tonight, I'll push up a PR, but if I don't get to it by Friday, I saw we release 1.3.0 without them.

**Comment by cquiroz** [comment]
sure, we can wait
