### ISSUE TITLE
How to use Percent with Money

### ISSUE THREAD

**Issue by bytecodeguru** [typelevel/squants#233]
Use case: add tax percent to net money amount.

Instead of using `BigDecimal`:
```scala
val net = EUR(100)
val tax = BigDecimal(22) / 100
val totalIncludingTaxes: Money  = net + net * tax
```

Is it possible to improve the example using `Percent`?

**Comment by garyKeorkunian** [comment]
@bytecodeguru So the idea would be that you could do this?:

```scala
val net = EUR(100)
val tax = 22.percent
val totalIncludingTax: Money = net + net * tax
```

**Comment by garyKeorkunian** [comment]
I think this speaks to a bigger idea.  Dimensionless values should be able to be used in any operation where standard numeric types can be used.

It seems to me that if we create an implicit conversion from Dimensionless to Double available, that should do the trick for this use case and many others.

Thoughts?

**Comment by bytecodeguru** [comment]
Yes, I feel the same. This calls for something bigger than my use case.

I like your solution idea, but perhaps it should disallow expressions like 

```scala
val totalIncludingTaxes = EUR(100) + 22.percent // + instead of * should be a typo/bug
val whatIsThis = 42.percent + 2.dozen // what would this mean?
```

and it should pay attention to Money's implementation that depends on BigDecimal rather than Double.

**Comment by garyKeorkunian** [comment]
Yes, your first example here would not be allowed, even with the conversion, as you can not add a Dimensionless nor a Double to a Money (or any other dimensional value). 

The second example is currently allowed as Percent and Dozen are both Dimensionless values.  The result would be 24.42.each.  It's syntactically valid, even if semantically strange.

I've done the work on this already and will have PR for review soon.

Before I do, I'll look at the BigDecimal issue and attempt to ensure no loss of precision when performing these ops.
