### ISSUE TITLE
QuantityRange throws spurious exceptions

### ISSUE THREAD

**Issue by derekmorr** [typelevel/squants#242]
`QuantityRange` requires that `upper` is strictly greater than `lower`, but the exception it throws claims upper must be >= lower:

```scala
case class QuantityRange[A <: Quantity[A]](lower: A, upper: A) {
  if (lower >= upper) throw new IllegalArgumentException("QuantityRange upper bound must be greater than or equal to the lower bound")
```

We should either fix the conditional check or the error message.

For reference, the Scala standard library, doesn't work when lower == upper:

```scala
scala> val r = Range(1,1)
r: scala.collection.immutable.Range = Range()

scala> r.contains(1)
res4: Boolean = false
```

So perhaps we should leave the conditional in place and change the error message.

I'd like to get this fixed as part of 1.3.0.

**Comment by cquiroz** [comment]
Ideally we wouldn't be throwing exceptions on the constructor
