### ISSUE TITLE
Add physical constants

### ISSUE THREAD

**Issue by underscorenico** [typelevel/squants#257]
An object could be added, containing (some ?) known and widely used physical constants. This constants will be very practical for conversions.
A comprehensive list can be found here: http://physics.nist.gov/cuu/pdf/all_2002.pdf

**Comment by cquiroz** [comment]
I'd be interested on taking this unless somebody else is already working it

**Comment by garyKeorkunian** [comment]
There are a few constants already defined.  The can be found in the package object of the of sub-package that contains that unit.  For example ...

```
package object motion {
   ...
   lazy val SpeedOfLight = Velocity(Meters(299792458e8), Seconds(1))
   ...
}
```

It looks like only the thermo, electro and motion sub-packages currently define a few.

I'm not sure if these package objects are the best place for them.  Perhaps a PhysicalConstants object which contains them all (or one per logical category) makes sense.

Also, the energy sub-package defines a formula for Kinetic Energy.  In addition to the physical constants, perhaps there are other standard formulas we may wish to support.
