### ISSUE TITLE
upgrade to scala native 0.3

### ISSUE THREAD

**Issue by derekmorr** [typelevel/squants#266]
Scala Native 0.3 is out - https://github.com/scala-native/scala-native/releases/tag/v0.3.0. We should upgrade to it and see if we can remove some of the work-arounds we had to implement in the past.

**Comment by cquiroz** [comment]
I guess enabling tests would be my highest prioirity

**Comment by shadaj** [comment]
I can work on upgrading Scala Native. I'm not sure if it will be possible to remove the workarounds though because porting string formatting is still a work-in-progress.

**Comment by derekmorr** [comment]
https://github.com/scalatest/scalatest/issues/1112 is the scalatest issue for scala native support.
