### ISSUE TITLE
Dividing quantity of TimeDerivative[A] by quantity of A

### ISSUE THREAD

**Issue by psung** [typelevel/squants#299]
It would be nice if `TimeDerivative[A]` implemented a method `def /(that: A): Frequency` so that for example you could write:

```
// currently this doesn't work
5.metersPerSecond / 2.meters
=> 2.5 Hz
```

This seems straightforward, and I hope uncontroversial, given that you can write all of the following:

```
2.meters / 5.metersPerSecond
=> 0.4 s

// this is my workaround currently for computing the above
1 / (2.meters / 5.metersPerSecond)
=> 2.5 Hz

2.meters * 2.5.Hz
=> 5.0 m/s
```

**Comment by hunterpayne** [comment]
I think this is the implementation you want.  Add this to the TimeDerivative trait in TimeDerivative.scala.

  def /(that: A): Frequency = 
    Hertz(timeIntegrated / (that / this.time.toSeconds))

Maybe you could make a PR for this.  Don't forget to add tests for this to the correct specs...
