### ISSUE TITLE
Kelvin symbol is incorrect

### ISSUE THREAD

**Issue by GerretS** [typelevel/squants#327]
The default symbol for Kelvin as given in
https://github.com/typelevel/squants/blob/037d3adb1ddbe47be8a74b8fe61f323564fedf66/shared/src/main/scala/squants/thermal/Temperature.scala#L188

is incorrect. Because the Kelvin units are related to an absolute scale, unlike the other temperature scales, it should not have the degree symbol `°`.

Sources:
BIPM, the official maintainers of the SI:
https://www.bipm.org/en/publications/si-brochure/kelvin.html
> The definition of the unit [...] the temperature 273.16 K, so defining the unit. The 13th CGPM (1967/68, Resolution 3) adopted the name **kelvin, symbol K,** instead of "degree Kelvin", symbol °K, 

Wikipedia corroborates this:
https://en.wikipedia.org/wiki/Kelvin
> The kelvin (symbol: K) is the base unit of temperature in the International System of Units (SI). 

Please change the default symbol for Kelvin to `K` in Squants.

**Comment by cquiroz** [comment]
Thanks, this looks good especially With the sources cited. Would you send a PR?
