### ISSUE TITLE
Better support for radioactivity units

### ISSUE THREAD

**Issue by hunterpayne** [typelevel/squants#336]
There are several missing types for doing calculations around radioactivity.

1) A unit measuring disintegration rates (ie Curie, Becquerel, and Rutherford) which is often called Activity
2) A unit measuring area * time (ie SquareMeterSeconds) which I call AreaTime (used to quantify exposure)
3) A unit measuring ParticleFlux (ie BecquerelsPerSquareMeterSecond)
4) A unit measuring equivalent/effective/committed dose

Also, adding ErgsPerGram to SpecificEnergy

Also, conversions between AreaTime, Area and Time

**Comment by hunterpayne** [comment]
https://github.com/typelevel/squants/pull/337

**Comment by garyKeorkunian** [comment]
Fixed by #337
