### ISSUE TITLE
Remove json module?

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#358]
It seems odd to me that we have support for a particular json lib (json4s) I'd expect that to live in a separate project/repo along other json encoders (circe, etc)

WDYT?

**Comment by ybasket** [comment]
Such modules could also live inside/next to the JSON libraries, see the discussion here:
https://github.com/circe/circe/pull/1111

**Comment by larsrh** [comment]
json4s is currently only a test dependency. My initial attempts suggest that this dependency in particular will be hard to port. So maybe just remove those tests?
