### ISSUE TITLE
Semantic Currency equality

### ISSUE THREAD

**Issue by tomasherman** [typelevel/squants#481]
Hi,

Is there some reason why `Currency` case class doesn't have equality implemented? In my usecase, im trying to use Currency on both server and client (scala.js), but the issue is that after i create Currency using the constructor during deserialisation, the equality will never work as there is no notion of 'semantic equality', just referential equality if i understand correctly.

Would you be open to adding semantical equals?

Thanks

**Comment by cquiroz** [comment]
No reason really. Feel free to send a PR

**Comment by tomasherman** [comment]
Would it be possible to have this released any time soon pls? :)

**Comment by cquiroz** [comment]
Done, see version 1.8.2

**Comment by tomasherman** [comment]
thanks!
