### ISSUE TITLE
Minutes symbol should be `min`

### ISSUE THREAD

**Issue by Lasering** [typelevel/squants#483]
According to [Wikipedia](https://en.wikipedia.org/wiki/Minute) the [SI symbol](https://en.wikipedia.org/wiki/Non-SI_units_mentioned_in_the_SI) for minute is `min` and not `m`. `m` is very easily confused with meters.

**Comment by cquiroz** [comment]
Thanks for the report. Would you be interested on making a PR?

**Comment by Lasering** [comment]
@cquiroz done
