### ISSUE TITLE
Kinetic energy calculations

### ISSUE THREAD

**Issue by leo-dur** [typelevel/squants#84]
Hi,

I'm trying to use squants to do some kinetic energy calculations :

val v1 = Meters(1.0)/Seconds(1.0)
val m1 = Kilograms(1.0)

val ek1 = 1/2 \* m1 \* v1 \* v1
val ek2 = 1/2 \* m1 \* (v1 \* v1)

But the last two lines don't compile (ek1 because operator \* is not define between one momentum and one velocity and ek2 because operator \* is not define between two velocities). 

Maybe I did something wrong, but I'm wondering if there is a way to do some kinetic energy calculations without define new operator *.

**Comment by bbarker** [comment]
Curious if it would be good to open an issue for discussing the more general issue of intermediate non-quantity values, or has this been resolved in some form?
